// AUTO-GENERATED by scripts/sync-game-ids.py — do not edit by hand.
// Source of truth: /Users/yin/code/games/games/games.json
//
// This file binds the game's permanent UUID (from games.json) to the
// browser's window so the @shared/runtime/getGameUuid() resolver can
// pick it up. main.tsx must import this file once at boot.

(window as any).__GAME_UUID__ = '2144a117-01c0-4f4a-9831-6610264bc917';
